# Configuración de la simulación
# La consulta a ejecutar por cada hilo. Si la tabla no existe, el programa
# intentará crearla automáticamente y meter una fila de prueba (para que
# rs.next() devuelva true.
# Puedes definir varias consultas separadas por punto y coma y el simulador
# escogera una al azar para cada petición.
#queries=SELECT * FROM usuario LIMIT 1;SELECT 1
query=SELECT * FROM usuario LIMIT 1

# cantidad de muestras; puede ser un solo número o una lista separada por comas
samples=20
#numero ejemplo: samples=100,500,1000

# reintentos antes de marcar un fallo
retries=3

# SQL de inicialización opcional (se ejecuta antes de comenzar).
#init_sql=CREATE TABLE IF NOT EXISTS usuario(id serial primary key);
